# Generated by Django 5.2.1 on 2025-05-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('toggle_on', 'Toggle On'), ('toggle_off', 'Toggle Off'), ('auto_disable', 'Auto Disable')], max_length=20)),
                ('actor', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='FlagDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='flags.featureflag')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='flags.featureflag')),
            ],
            options={
                'unique_together': {('flag', 'depends_on')},
            },
        ),
    ]
